# name: Run lint on pull requests

# on:
#   push:
#     branches: 
#     - master
#     - development
      
#   pull_request:
#     branches: 
#     - master
#     - development

# jobs:
#   lint:
#     name: Check code style
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout source code
#         uses: actions/checkout@v2
#       - name: Install Flutter
#         uses: subosito/flutter-action@v1
#         with:
#           channel: 'stable'
#       - name: Get packages in a Flutter project
#         run: flutter pub get
#       - name: Run lint
#         uses: kitek/dartanalyzer-annotations-action@v1  
#         env:
#           GITHUB_TOKEN: ${{ github.token }}
#         with:
#           check_name: 'Check code style'
#           commit_sha: ${{ github.event.pull_request.head.sha }}
  
#   build:
#     runs-on: ubuntu-latest
#     container:
#       image:  google/dart:latest
#     steps:
#     - uses: actions/checkout@v2
#     - name: Install dependencies
#       run: pub get
#     - name: Run tests
#       run: pub run test
#     - name: Dartanalyzer annotations
#       uses: kitek/dartanalyzer-annotations-action@v1.1
#     - run: flutter pub get
#     - run: flutter packages pub run build_runner build
#     - run: flutter build aot
#     - run: flutter analyze
#     - run: flutter test --coverage .
#     - uses: codecov/codecov-action@v1.0.2
#       with:
#         token: ${{ secrets.CODECOV_TOKEN }}
  
    
    

